# These are supported funding model platforms

custom: ['https://paypal.me/wvdg44?country.x=CA&locale.x=en_US', 'https://psfmember.org/civicrm/contribute/transact?reset=1&id=2', 'https://www.pyinstaller.org/funding.html#funding-by-individuals']
